name: Verify

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  hosted_pool_linux:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup CFS
        uses: ./actions/setup
        with:
          feed-url: "https://pkgs.dev.azure.com/contoso/MyFeed/_packaging/MyFeed/"
          cfs-auth-token: "fake-token"
          nuget: true
          nuget-config: true
          npm-config: true

      - name: Validate Configuration
        shell: bash
        run: |
          echo "Validating CFS setup..."

          # Check environment variables are set (without exposing values)
          if [ -n "$CFS_ACCESSTOKEN" ]; then
            echo "✓ CFS_ACCESSTOKEN is set"
          else
            echo "✗ CFS_ACCESSTOKEN is not set"
            exit 1
          fi

          if [ -n "$VSS_NUGET_ACCESSTOKEN" ]; then
            echo "✓ VSS_NUGET_ACCESSTOKEN is set"
          else
            echo "✗ VSS_NUGET_ACCESSTOKEN is not set"
            exit 1
          fi

          if [ -n "$VSS_NUGET_URI_PREFIXES" ]; then
            echo "✓ VSS_NUGET_URI_PREFIXES is set to: $VSS_NUGET_URI_PREFIXES"
          else
            echo "✗ VSS_NUGET_URI_PREFIXES is not set"
            exit 1
          fi

          # Check NuGet plugins directory exists
          if [ -d ~/.nuget/plugins ]; then
            echo "✓ NuGet plugins directory exists"
            ls -la ~/.nuget/plugins
          else
            echo "✗ NuGet plugins directory not found"
            exit 1
          fi

          # Validate nuget.config exists and has proper structure
          if [ -f nuget.config ]; then
            echo "✓ nuget.config file exists"
            if grep -q "packageSources" nuget.config && grep -q "CFS-Feed" nuget.config; then
              echo "✓ nuget.config has proper structure"
            else
              echo "✗ nuget.config is missing required sections"
              exit 1
            fi
          else
            echo "✗ nuget.config file not found"
            exit 1
          fi

          # Validate .npmrc exists and has proper structure
          if [ -f ~/.npmrc ]; then
            echo "✓ .npmrc file exists"
            if grep -q "registry" ~/.npmrc && grep -q "github-actions" ~/.npmrc; then
              echo "✓ .npmrc has proper structure"
            else
              echo "✗ .npmrc is missing required configuration"
              exit 1
            fi
          else
            echo "✗ .npmrc file not found"
            exit 1
          fi

          echo "All validations passed!"

  hosted_pool_windows:
    name: Hosted Pool Windows
    runs-on: [windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup CFS
        uses: ./actions/setup
        with:
          feed-url: "https://pkgs.dev.azure.com/contoso/MyFeed/_packaging/MyFeed/"
          cfs-auth-token: "fake-token"
          nuget: true
          nuget-config: true
          npm-config: true
          encode-variable: true

      - name: Validate Configuration
        shell: bash
        run: |
          echo "CFS_ACCESSTOKEN="$CFS_ACCESSTOKEN
          echo "VSS_NUGET_ACCESSTOKEN="$VSS_NUGET_ACCESSTOKEN
          echo "VSS_NUGET_URI_PREFIXES="$VSS_NUGET_URI_PREFIXES
          ls ~/.nuget/plugins
          cat nuget.config
          cat ~/.npmrc
          env